=== JetBrains/teamcity-priority-queue/server/testData/build-queue-priorities.dtd
<?xml version='1.0' encoding='ISO-8859-1' ?>

<!ELEMENT priority-classes (priority-class*)>

<!ELEMENT priority-class (build-type*)>
<!ATTLIST priority-class
    id          CDATA #REQUIRED
    name        CDATA #REQUIRED
    priority    CDATA #REQUIRED
    description CDATA #IMPLIED>

<!ELEMENT build-type EMPTY>
<!ATTLIST build-type id CDATA #REQUIRED>

=== JetBrains/teamcity-priority-queue/server/testData/build-queue-priorities-removed-build-type.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE priority-classes SYSTEM "build-queue-priorities.dtd">

<priority-classes>

  <priority-class id="pc1" name="Inspections" priority="-1"
                  description="Low priority inspections">
    <build-type id="bt14"/>
    <build-type id="bt47"/>
    <build-type id="bt6"/>
  </priority-class>

  <priority-class id="pc2" name="Release" priority="5"
                  description="Soon to be released">
    <build-type id="bt1"/>
    <build-type id="bt3"/>
  </priority-class>

</priority-classes>
